package com.ratatoskr.shared.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CheckboxDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.SliderDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import com.ratatoskr.shared.api.GenerateRequest
import com.ratatoskr.shared.state.AppState
import kotlinx.coroutines.launch

/** Standalone generator. Mirrors #generator-modal. When opened from an
 * entry's "Generate" button (rather than the header's standalone
 * "Generate" action), `onUse` fills the caller's password field instead of
 * just displaying a value to copy. */
@Composable
fun GeneratorDialog(
    appState: AppState,
    onDismiss: () -> Unit,
    onUse: ((String) -> Unit)? = null,
) {
    var length by remember { mutableStateOf(20f) }
    var useUpper by remember { mutableStateOf(true) }
    var useLower by remember { mutableStateOf(true) }
    var useDigits by remember { mutableStateOf(true) }
    var useSymbols by remember { mutableStateOf(true) }
    var avoidAmbiguous by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    val scope = rememberCoroutineScope()

    suspend fun regenerate() {
        error = null
        try {
            val response = appState.api().generatePassword(
                GenerateRequest(
                    length = length.toInt(),
                    use_upper = useUpper,
                    use_lower = useLower,
                    use_digits = useDigits,
                    use_symbols = useSymbols,
                    avoid_ambiguous = avoidAmbiguous,
                )
            )
            generated = response.password
        } catch (e: Exception) {
            error = e.message ?: "Couldn't generate a password"
        }
    }

    LaunchedEffect(Unit) { regenerate() }

    Dialog(onDismissRequest = onDismiss) {
        Column(
            modifier = Modifier
                .widthIn(max = 400.dp).fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .background(RatatoskrColors.Panel, RoundedCornerShape(8.dp))
                .border(1.dp, RatatoskrColors.Hairline, RoundedCornerShape(8.dp))
                .padding(24.dp),
        ) {
            Text("Generate a password", style = MaterialTheme.typography.titleMedium, color = RatatoskrColors.Text)
            Spacer(Modifier.height(12.dp))

            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(RatatoskrColors.PanelAlt, RoundedCornerShape(4.dp))
                    .border(1.dp, RatatoskrColors.Hairline, RoundedCornerShape(4.dp))
                    .padding(12.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text(
                    generated,
                    style = MaterialTheme.typography.titleMedium,
                    color = RatatoskrColors.Verdigris,
                    fontFamily = FontFamily.Monospace,
                    modifier = Modifier.weight(1f),
                )
            }

            Text(
                "Length: ${length.toInt()}",
                style = MaterialTheme.typography.bodySmall,
                color = RatatoskrColors.TextMuted,
                modifier = Modifier.padding(top = 14.dp),
            )
            Slider(
                value = length,
                onValueChange = { length = it },
                onValueChangeFinished = { scope.launch { regenerate() } },
                valueRange = 8f..64f,
                colors = SliderDefaults.colors(thumbColor = RatatoskrColors.Brass, activeTrackColor = RatatoskrColors.Brass),
            )

            GenOption("Uppercase (A-Z)", useUpper) { useUpper = it; scope.launch { regenerate() } }
            GenOption("Lowercase (a-z)", useLower) { useLower = it; scope.launch { regenerate() } }
            GenOption("Digits (0-9)", useDigits) { useDigits = it; scope.launch { regenerate() } }
            GenOption("Symbols (!@#\$...)", useSymbols) { useSymbols = it; scope.launch { regenerate() } }
            GenOption("Avoid ambiguous characters (Il1O0)", avoidAmbiguous) { avoidAmbiguous = it; scope.launch { regenerate() } }

            ErrorText(error, modifier = Modifier.fillMaxWidth())

            Row(modifier = Modifier.fillMaxWidth().padding(top = 16.dp), horizontalArrangement = Arrangement.End) {
                GhostButton("Close", onClick = onDismiss)
                Spacer(Modifier.width(8.dp))
                if (onUse != null) {
                    PrimaryButton("Use this password", onClick = { onUse(generated); onDismiss() })
                } else {
                    PrimaryButton("Regenerate", onClick = { scope.launch { regenerate() } })
                }
            }
        }
    }
}

@Composable
private fun GenOption(label: String, checked: Boolean, onCheckedChange: (Boolean) -> Unit) {
    Row(modifier = Modifier.fillMaxWidth().padding(top = 6.dp), verticalAlignment = Alignment.CenterVertically) {
        Checkbox(
            checked = checked,
            onCheckedChange = onCheckedChange,
            colors = CheckboxDefaults.colors(checkedColor = RatatoskrColors.Brass),
        )
        Text(label, style = MaterialTheme.typography.bodyMedium, color = RatatoskrColors.Text)
    }
}
